export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const FETCH_ALL = 'FETCH_ALL';

export const AUTH ='AUTH';
export const LOGOUT ='LOGOUT';


export const CREATE_MOVIE = 'CREATE_MOVIE';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const FETCH_ALL_MOVIES = 'FETCH_ALL_MOVIES';

export const CREATE_MOVIE_LIST = 'CREATE_MOVIE_LIST';
export const UPDATE_MOVIE_LIST = 'UPDATE_MOVIE_LIST';
export const DELETE_MOVIE_LIST = 'DELETE_MOVIE_LIST';
export const FETCH_ALL_MOVIE_LISTS = 'FETCH_ALL_MOVIE_LISTS';
export const FETCH_MOVIE_LIST = 'FETCH_MOVIE_LIST';
export const FETCH_LIST_OF_MOVIES = 'FETCH_LIST_OF_MOVIES';


export const FETCH_ALL_USERS ='FETCH_ALL_USERS';
export const FETCH_USER ='FETCH_USER';
export const UPDATE_USER ='UPDATE_USER';